spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/factusapp_dev
    username: factusapp
    password: factusapp123

  jpa:
    show-sql: true

logging:
  level:
    com.factusapp: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
